//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.6
//
// <auto-generated>
//
// Generated from file `XXXJobTransaction.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

#include <XXXJobTransaction.h>
#include <IceUtil/PushDisableWarnings.h>
#include <Ice/LocalException.h>
#include <Ice/ValueFactory.h>
#include <Ice/OutgoingAsync.h>
#include <Ice/InputStream.h>
#include <Ice/OutputStream.h>
#include <IceUtil/PopDisableWarnings.h>

#if defined(_MSC_VER)
#   pragma warning(disable:4458) // declaration of ... hides class member
#elif defined(__clang__)
#   pragma clang diagnostic ignored "-Wshadow"
#elif defined(__GNUC__)
#   pragma GCC diagnostic ignored "-Wshadow"
#endif

#ifndef ICE_IGNORE_VERSION
#   if ICE_INT_VERSION / 100 != 307
#       error Ice version mismatch!
#   endif
#   if ICE_INT_VERSION % 100 >= 50
#       error Beta header file detected
#   endif
#   if ICE_INT_VERSION % 100 < 6
#       error Ice patch level mismatch!
#   endif
#endif

#ifdef ICE_CPP11_MAPPING // C++11 mapping

namespace
{

const ::std::string iceC_XXXJobTrans_XXXJobWorker_ids[2] =
{
    "::Ice::Object",
    "::XXXJobTrans::XXXJobWorker"
};
const ::std::string iceC_XXXJobTrans_XXXJobWorker_ops[] =
{
    "ice_id",
    "ice_ids",
    "ice_isA",
    "ice_ping",
    "processXXXItem",
    "processYYYItem",
    "shutdown"
};
const ::std::string iceC_XXXJobTrans_XXXJobWorker_processXXXItem_name = "processXXXItem";
const ::std::string iceC_XXXJobTrans_XXXJobWorker_processYYYItem_name = "processYYYItem";
const ::std::string iceC_XXXJobTrans_XXXJobWorker_shutdown_name = "shutdown";

const ::std::string iceC_XXXJobTrans_XXXJobDirector_ids[2] =
{
    "::Ice::Object",
    "::XXXJobTrans::XXXJobDirector"
};
const ::std::string iceC_XXXJobTrans_XXXJobDirector_ops[] =
{
    "compete",
    "ice_id",
    "ice_ids",
    "ice_isA",
    "ice_ping",
    "onXXXResult",
    "onYYYResult"
};
const ::std::string iceC_XXXJobTrans_XXXJobDirector_compete_name = "compete";
const ::std::string iceC_XXXJobTrans_XXXJobDirector_onXXXResult_name = "onXXXResult";
const ::std::string iceC_XXXJobTrans_XXXJobDirector_onYYYResult_name = "onYYYResult";

}

bool
XXXJobTrans::XXXJobWorker::ice_isA(::std::string s, const ::Ice::Current&) const
{
    return ::std::binary_search(iceC_XXXJobTrans_XXXJobWorker_ids, iceC_XXXJobTrans_XXXJobWorker_ids + 2, s);
}

::std::vector<::std::string>
XXXJobTrans::XXXJobWorker::ice_ids(const ::Ice::Current&) const
{
    return ::std::vector<::std::string>(&iceC_XXXJobTrans_XXXJobWorker_ids[0], &iceC_XXXJobTrans_XXXJobWorker_ids[2]);
}

::std::string
XXXJobTrans::XXXJobWorker::ice_id(const ::Ice::Current&) const
{
    return ice_staticId();
}

const ::std::string&
XXXJobTrans::XXXJobWorker::ice_staticId()
{
    static const ::std::string typeId = "::XXXJobTrans::XXXJobWorker";
    return typeId;
}

/// \cond INTERNAL
bool
XXXJobTrans::XXXJobWorker::_iceD_processXXXItem(::IceInternal::Incoming& inS, const ::Ice::Current& current)
{
    _iceCheckMode(::Ice::OperationMode::Normal, current.mode);
    auto istr = inS.startReadParams();
    ::std::pair<const ::Ice::Byte*, const ::Ice::Byte*> iceP_data;
    istr->readAll(iceP_data);
    inS.endReadParams();
    this->processXXXItem(::std::move(iceP_data), current);
    inS.writeEmptyParams();
    return true;
}
/// \endcond

/// \cond INTERNAL
bool
XXXJobTrans::XXXJobWorker::_iceD_processYYYItem(::IceInternal::Incoming& inS, const ::Ice::Current& current)
{
    _iceCheckMode(::Ice::OperationMode::Normal, current.mode);
    auto istr = inS.startReadParams();
    ::std::pair<const ::Ice::Byte*, const ::Ice::Byte*> iceP_data;
    istr->readAll(iceP_data);
    inS.endReadParams();
    this->processYYYItem(::std::move(iceP_data), current);
    inS.writeEmptyParams();
    return true;
}
/// \endcond

/// \cond INTERNAL
bool
XXXJobTrans::XXXJobWorker::_iceD_shutdown(::IceInternal::Incoming& inS, const ::Ice::Current& current)
{
    _iceCheckMode(::Ice::OperationMode::Normal, current.mode);
    inS.readEmptyParams();
    this->shutdown(current);
    inS.writeEmptyParams();
    return true;
}
/// \endcond

/// \cond INTERNAL
bool
XXXJobTrans::XXXJobWorker::_iceDispatch(::IceInternal::Incoming& in, const ::Ice::Current& current)
{
    ::std::pair<const ::std::string*, const ::std::string*> r = ::std::equal_range(iceC_XXXJobTrans_XXXJobWorker_ops, iceC_XXXJobTrans_XXXJobWorker_ops + 7, current.operation);
    if(r.first == r.second)
    {
        throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
    }

    switch(r.first - iceC_XXXJobTrans_XXXJobWorker_ops)
    {
        case 0:
        {
            return _iceD_ice_id(in, current);
        }
        case 1:
        {
            return _iceD_ice_ids(in, current);
        }
        case 2:
        {
            return _iceD_ice_isA(in, current);
        }
        case 3:
        {
            return _iceD_ice_ping(in, current);
        }
        case 4:
        {
            return _iceD_processXXXItem(in, current);
        }
        case 5:
        {
            return _iceD_processYYYItem(in, current);
        }
        case 6:
        {
            return _iceD_shutdown(in, current);
        }
        default:
        {
            assert(false);
            throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
        }
    }
}
/// \endcond

bool
XXXJobTrans::XXXJobDirector::ice_isA(::std::string s, const ::Ice::Current&) const
{
    return ::std::binary_search(iceC_XXXJobTrans_XXXJobDirector_ids, iceC_XXXJobTrans_XXXJobDirector_ids + 2, s);
}

::std::vector<::std::string>
XXXJobTrans::XXXJobDirector::ice_ids(const ::Ice::Current&) const
{
    return ::std::vector<::std::string>(&iceC_XXXJobTrans_XXXJobDirector_ids[0], &iceC_XXXJobTrans_XXXJobDirector_ids[2]);
}

::std::string
XXXJobTrans::XXXJobDirector::ice_id(const ::Ice::Current&) const
{
    return ice_staticId();
}

const ::std::string&
XXXJobTrans::XXXJobDirector::ice_staticId()
{
    static const ::std::string typeId = "::XXXJobTrans::XXXJobDirector";
    return typeId;
}

/// \cond INTERNAL
bool
XXXJobTrans::XXXJobDirector::_iceD_compete(::IceInternal::Incoming& inS, const ::Ice::Current& current)
{
    _iceCheckMode(::Ice::OperationMode::Normal, current.mode);
    auto istr = inS.startReadParams();
    ::std::shared_ptr<XXXJobWorkerPrx> iceP_worker;
    istr->readAll(iceP_worker);
    inS.endReadParams();
    bool ret = this->compete(::std::move(iceP_worker), current);
    auto ostr = inS.startWriteParams();
    ostr->writeAll(ret);
    inS.endWriteParams();
    return true;
}
/// \endcond

/// \cond INTERNAL
bool
XXXJobTrans::XXXJobDirector::_iceD_onXXXResult(::IceInternal::Incoming& inS, const ::Ice::Current& current)
{
    _iceCheckMode(::Ice::OperationMode::Normal, current.mode);
    auto istr = inS.startReadParams();
    int iceP_result;
    istr->readAll(iceP_result);
    inS.endReadParams();
    this->onXXXResult(iceP_result, current);
    inS.writeEmptyParams();
    return true;
}
/// \endcond

/// \cond INTERNAL
bool
XXXJobTrans::XXXJobDirector::_iceD_onYYYResult(::IceInternal::Incoming& inS, const ::Ice::Current& current)
{
    _iceCheckMode(::Ice::OperationMode::Normal, current.mode);
    auto istr = inS.startReadParams();
    int iceP_result;
    istr->readAll(iceP_result);
    inS.endReadParams();
    this->onYYYResult(iceP_result, current);
    inS.writeEmptyParams();
    return true;
}
/// \endcond

/// \cond INTERNAL
bool
XXXJobTrans::XXXJobDirector::_iceDispatch(::IceInternal::Incoming& in, const ::Ice::Current& current)
{
    ::std::pair<const ::std::string*, const ::std::string*> r = ::std::equal_range(iceC_XXXJobTrans_XXXJobDirector_ops, iceC_XXXJobTrans_XXXJobDirector_ops + 7, current.operation);
    if(r.first == r.second)
    {
        throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
    }

    switch(r.first - iceC_XXXJobTrans_XXXJobDirector_ops)
    {
        case 0:
        {
            return _iceD_compete(in, current);
        }
        case 1:
        {
            return _iceD_ice_id(in, current);
        }
        case 2:
        {
            return _iceD_ice_ids(in, current);
        }
        case 3:
        {
            return _iceD_ice_isA(in, current);
        }
        case 4:
        {
            return _iceD_ice_ping(in, current);
        }
        case 5:
        {
            return _iceD_onXXXResult(in, current);
        }
        case 6:
        {
            return _iceD_onYYYResult(in, current);
        }
        default:
        {
            assert(false);
            throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
        }
    }
}
/// \endcond

/// \cond INTERNAL
void
XXXJobTrans::XXXJobWorkerPrx::_iceI_processXXXItem(const ::std::shared_ptr<::IceInternal::OutgoingAsyncT<void>>& outAsync, const ::std::pair<const ::Ice::Byte*, const ::Ice::Byte*>& iceP_data, const ::Ice::Context& context)
{
    outAsync->invoke(iceC_XXXJobTrans_XXXJobWorker_processXXXItem_name, ::Ice::OperationMode::Normal, ::Ice::FormatType::DefaultFormat, context,
        [&](::Ice::OutputStream* ostr)
        {
            ostr->writeAll(iceP_data);
        },
        nullptr);
}
/// \endcond

/// \cond INTERNAL
void
XXXJobTrans::XXXJobWorkerPrx::_iceI_processYYYItem(const ::std::shared_ptr<::IceInternal::OutgoingAsyncT<void>>& outAsync, const ::std::pair<const ::Ice::Byte*, const ::Ice::Byte*>& iceP_data, const ::Ice::Context& context)
{
    outAsync->invoke(iceC_XXXJobTrans_XXXJobWorker_processYYYItem_name, ::Ice::OperationMode::Normal, ::Ice::FormatType::DefaultFormat, context,
        [&](::Ice::OutputStream* ostr)
        {
            ostr->writeAll(iceP_data);
        },
        nullptr);
}
/// \endcond

/// \cond INTERNAL
void
XXXJobTrans::XXXJobWorkerPrx::_iceI_shutdown(const ::std::shared_ptr<::IceInternal::OutgoingAsyncT<void>>& outAsync, const ::Ice::Context& context)
{
    outAsync->invoke(iceC_XXXJobTrans_XXXJobWorker_shutdown_name, ::Ice::OperationMode::Normal, ::Ice::FormatType::DefaultFormat, context,
        nullptr,
        nullptr);
}
/// \endcond

/// \cond INTERNAL
::std::shared_ptr<::Ice::ObjectPrx>
XXXJobTrans::XXXJobWorkerPrx::_newInstance() const
{
    return ::IceInternal::createProxy<XXXJobWorkerPrx>();
}
/// \endcond

const ::std::string&
XXXJobTrans::XXXJobWorkerPrx::ice_staticId()
{
    return XXXJobWorker::ice_staticId();
}

/// \cond INTERNAL
void
XXXJobTrans::XXXJobDirectorPrx::_iceI_compete(const ::std::shared_ptr<::IceInternal::OutgoingAsyncT<bool>>& outAsync, const ::std::shared_ptr<XXXJobWorkerPrx>& iceP_worker, const ::Ice::Context& context)
{
    _checkTwowayOnly(iceC_XXXJobTrans_XXXJobDirector_compete_name);
    outAsync->invoke(iceC_XXXJobTrans_XXXJobDirector_compete_name, ::Ice::OperationMode::Normal, ::Ice::FormatType::DefaultFormat, context,
        [&](::Ice::OutputStream* ostr)
        {
            ostr->writeAll(iceP_worker);
        },
        nullptr);
}
/// \endcond

/// \cond INTERNAL
void
XXXJobTrans::XXXJobDirectorPrx::_iceI_onXXXResult(const ::std::shared_ptr<::IceInternal::OutgoingAsyncT<void>>& outAsync, int iceP_result, const ::Ice::Context& context)
{
    outAsync->invoke(iceC_XXXJobTrans_XXXJobDirector_onXXXResult_name, ::Ice::OperationMode::Normal, ::Ice::FormatType::DefaultFormat, context,
        [&](::Ice::OutputStream* ostr)
        {
            ostr->writeAll(iceP_result);
        },
        nullptr);
}
/// \endcond

/// \cond INTERNAL
void
XXXJobTrans::XXXJobDirectorPrx::_iceI_onYYYResult(const ::std::shared_ptr<::IceInternal::OutgoingAsyncT<void>>& outAsync, int iceP_result, const ::Ice::Context& context)
{
    outAsync->invoke(iceC_XXXJobTrans_XXXJobDirector_onYYYResult_name, ::Ice::OperationMode::Normal, ::Ice::FormatType::DefaultFormat, context,
        [&](::Ice::OutputStream* ostr)
        {
            ostr->writeAll(iceP_result);
        },
        nullptr);
}
/// \endcond

/// \cond INTERNAL
::std::shared_ptr<::Ice::ObjectPrx>
XXXJobTrans::XXXJobDirectorPrx::_newInstance() const
{
    return ::IceInternal::createProxy<XXXJobDirectorPrx>();
}
/// \endcond

const ::std::string&
XXXJobTrans::XXXJobDirectorPrx::ice_staticId()
{
    return XXXJobDirector::ice_staticId();
}

#else // C++98 mapping

namespace
{

const ::std::string iceC_XXXJobTrans_XXXJobWorker_processXXXItem_name = "processXXXItem";

const ::std::string iceC_XXXJobTrans_XXXJobWorker_processYYYItem_name = "processYYYItem";

const ::std::string iceC_XXXJobTrans_XXXJobWorker_shutdown_name = "shutdown";

const ::std::string iceC_XXXJobTrans_XXXJobDirector_compete_name = "compete";

const ::std::string iceC_XXXJobTrans_XXXJobDirector_onXXXResult_name = "onXXXResult";

const ::std::string iceC_XXXJobTrans_XXXJobDirector_onYYYResult_name = "onYYYResult";

}

/// \cond INTERNAL
::IceProxy::Ice::Object* ::IceProxy::XXXJobTrans::upCast(XXXJobWorker* p) { return p; }

void
::IceProxy::XXXJobTrans::_readProxy(::Ice::InputStream* istr, ::IceInternal::ProxyHandle< XXXJobWorker>& v)
{
    ::Ice::ObjectPrx proxy;
    istr->read(proxy);
    if(!proxy)
    {
        v = 0;
    }
    else
    {
        v = new XXXJobWorker;
        v->_copyFrom(proxy);
    }
}
/// \endcond

::Ice::AsyncResultPtr
IceProxy::XXXJobTrans::XXXJobWorker::_iceI_begin_processXXXItem(const ::std::pair<const ::Ice::Byte*, const ::Ice::Byte*>& iceP_data, const ::Ice::Context& context, const ::IceInternal::CallbackBasePtr& del, const ::Ice::LocalObjectPtr& cookie, bool sync)
{
    ::IceInternal::OutgoingAsyncPtr result = new ::IceInternal::CallbackOutgoing(this, iceC_XXXJobTrans_XXXJobWorker_processXXXItem_name, del, cookie, sync);
    try
    {
        result->prepare(iceC_XXXJobTrans_XXXJobWorker_processXXXItem_name, ::Ice::Normal, context);
        ::Ice::OutputStream* ostr = result->startWriteParams(::Ice::DefaultFormat);
        ostr->write(iceP_data);
        result->endWriteParams();
        result->invoke(iceC_XXXJobTrans_XXXJobWorker_processXXXItem_name);
    }
    catch(const ::Ice::Exception& ex)
    {
        result->abort(ex);
    }
    return result;
}

void
IceProxy::XXXJobTrans::XXXJobWorker::end_processXXXItem(const ::Ice::AsyncResultPtr& result)
{
    _end(result, iceC_XXXJobTrans_XXXJobWorker_processXXXItem_name);
}

::Ice::AsyncResultPtr
IceProxy::XXXJobTrans::XXXJobWorker::_iceI_begin_processYYYItem(const ::std::pair<const ::Ice::Byte*, const ::Ice::Byte*>& iceP_data, const ::Ice::Context& context, const ::IceInternal::CallbackBasePtr& del, const ::Ice::LocalObjectPtr& cookie, bool sync)
{
    ::IceInternal::OutgoingAsyncPtr result = new ::IceInternal::CallbackOutgoing(this, iceC_XXXJobTrans_XXXJobWorker_processYYYItem_name, del, cookie, sync);
    try
    {
        result->prepare(iceC_XXXJobTrans_XXXJobWorker_processYYYItem_name, ::Ice::Normal, context);
        ::Ice::OutputStream* ostr = result->startWriteParams(::Ice::DefaultFormat);
        ostr->write(iceP_data);
        result->endWriteParams();
        result->invoke(iceC_XXXJobTrans_XXXJobWorker_processYYYItem_name);
    }
    catch(const ::Ice::Exception& ex)
    {
        result->abort(ex);
    }
    return result;
}

void
IceProxy::XXXJobTrans::XXXJobWorker::end_processYYYItem(const ::Ice::AsyncResultPtr& result)
{
    _end(result, iceC_XXXJobTrans_XXXJobWorker_processYYYItem_name);
}

::Ice::AsyncResultPtr
IceProxy::XXXJobTrans::XXXJobWorker::_iceI_begin_shutdown(const ::Ice::Context& context, const ::IceInternal::CallbackBasePtr& del, const ::Ice::LocalObjectPtr& cookie, bool sync)
{
    ::IceInternal::OutgoingAsyncPtr result = new ::IceInternal::CallbackOutgoing(this, iceC_XXXJobTrans_XXXJobWorker_shutdown_name, del, cookie, sync);
    try
    {
        result->prepare(iceC_XXXJobTrans_XXXJobWorker_shutdown_name, ::Ice::Normal, context);
        result->writeEmptyParams();
        result->invoke(iceC_XXXJobTrans_XXXJobWorker_shutdown_name);
    }
    catch(const ::Ice::Exception& ex)
    {
        result->abort(ex);
    }
    return result;
}

void
IceProxy::XXXJobTrans::XXXJobWorker::end_shutdown(const ::Ice::AsyncResultPtr& result)
{
    _end(result, iceC_XXXJobTrans_XXXJobWorker_shutdown_name);
}

/// \cond INTERNAL
::IceProxy::Ice::Object*
IceProxy::XXXJobTrans::XXXJobWorker::_newInstance() const
{
    return new XXXJobWorker;
}
/// \endcond

const ::std::string&
IceProxy::XXXJobTrans::XXXJobWorker::ice_staticId()
{
    return ::XXXJobTrans::XXXJobWorker::ice_staticId();
}

/// \cond INTERNAL
::IceProxy::Ice::Object* ::IceProxy::XXXJobTrans::upCast(XXXJobDirector* p) { return p; }

void
::IceProxy::XXXJobTrans::_readProxy(::Ice::InputStream* istr, ::IceInternal::ProxyHandle< XXXJobDirector>& v)
{
    ::Ice::ObjectPrx proxy;
    istr->read(proxy);
    if(!proxy)
    {
        v = 0;
    }
    else
    {
        v = new XXXJobDirector;
        v->_copyFrom(proxy);
    }
}
/// \endcond

::Ice::AsyncResultPtr
IceProxy::XXXJobTrans::XXXJobDirector::_iceI_begin_compete(const ::XXXJobTrans::XXXJobWorkerPrx& iceP_worker, const ::Ice::Context& context, const ::IceInternal::CallbackBasePtr& del, const ::Ice::LocalObjectPtr& cookie, bool sync)
{
    _checkTwowayOnly(iceC_XXXJobTrans_XXXJobDirector_compete_name, sync);
    ::IceInternal::OutgoingAsyncPtr result = new ::IceInternal::CallbackOutgoing(this, iceC_XXXJobTrans_XXXJobDirector_compete_name, del, cookie, sync);
    try
    {
        result->prepare(iceC_XXXJobTrans_XXXJobDirector_compete_name, ::Ice::Normal, context);
        ::Ice::OutputStream* ostr = result->startWriteParams(::Ice::DefaultFormat);
        ostr->write(iceP_worker);
        result->endWriteParams();
        result->invoke(iceC_XXXJobTrans_XXXJobDirector_compete_name);
    }
    catch(const ::Ice::Exception& ex)
    {
        result->abort(ex);
    }
    return result;
}

bool
IceProxy::XXXJobTrans::XXXJobDirector::end_compete(const ::Ice::AsyncResultPtr& result)
{
    ::Ice::AsyncResult::_check(result, this, iceC_XXXJobTrans_XXXJobDirector_compete_name);
    bool ret;
    if(!result->_waitForResponse())
    {
        try
        {
            result->_throwUserException();
        }
        catch(const ::Ice::UserException& ex)
        {
            throw ::Ice::UnknownUserException(__FILE__, __LINE__, ex.ice_id());
        }
    }
    ::Ice::InputStream* istr = result->_startReadParams();
    istr->read(ret);
    result->_endReadParams();
    return ret;
}

::Ice::AsyncResultPtr
IceProxy::XXXJobTrans::XXXJobDirector::_iceI_begin_onXXXResult(::Ice::Int iceP_result, const ::Ice::Context& context, const ::IceInternal::CallbackBasePtr& del, const ::Ice::LocalObjectPtr& cookie, bool sync)
{
    ::IceInternal::OutgoingAsyncPtr result = new ::IceInternal::CallbackOutgoing(this, iceC_XXXJobTrans_XXXJobDirector_onXXXResult_name, del, cookie, sync);
    try
    {
        result->prepare(iceC_XXXJobTrans_XXXJobDirector_onXXXResult_name, ::Ice::Normal, context);
        ::Ice::OutputStream* ostr = result->startWriteParams(::Ice::DefaultFormat);
        ostr->write(iceP_result);
        result->endWriteParams();
        result->invoke(iceC_XXXJobTrans_XXXJobDirector_onXXXResult_name);
    }
    catch(const ::Ice::Exception& ex)
    {
        result->abort(ex);
    }
    return result;
}

void
IceProxy::XXXJobTrans::XXXJobDirector::end_onXXXResult(const ::Ice::AsyncResultPtr& result)
{
    _end(result, iceC_XXXJobTrans_XXXJobDirector_onXXXResult_name);
}

::Ice::AsyncResultPtr
IceProxy::XXXJobTrans::XXXJobDirector::_iceI_begin_onYYYResult(::Ice::Int iceP_result, const ::Ice::Context& context, const ::IceInternal::CallbackBasePtr& del, const ::Ice::LocalObjectPtr& cookie, bool sync)
{
    ::IceInternal::OutgoingAsyncPtr result = new ::IceInternal::CallbackOutgoing(this, iceC_XXXJobTrans_XXXJobDirector_onYYYResult_name, del, cookie, sync);
    try
    {
        result->prepare(iceC_XXXJobTrans_XXXJobDirector_onYYYResult_name, ::Ice::Normal, context);
        ::Ice::OutputStream* ostr = result->startWriteParams(::Ice::DefaultFormat);
        ostr->write(iceP_result);
        result->endWriteParams();
        result->invoke(iceC_XXXJobTrans_XXXJobDirector_onYYYResult_name);
    }
    catch(const ::Ice::Exception& ex)
    {
        result->abort(ex);
    }
    return result;
}

void
IceProxy::XXXJobTrans::XXXJobDirector::end_onYYYResult(const ::Ice::AsyncResultPtr& result)
{
    _end(result, iceC_XXXJobTrans_XXXJobDirector_onYYYResult_name);
}

/// \cond INTERNAL
::IceProxy::Ice::Object*
IceProxy::XXXJobTrans::XXXJobDirector::_newInstance() const
{
    return new XXXJobDirector;
}
/// \endcond

const ::std::string&
IceProxy::XXXJobTrans::XXXJobDirector::ice_staticId()
{
    return ::XXXJobTrans::XXXJobDirector::ice_staticId();
}

XXXJobTrans::XXXJobWorker::~XXXJobWorker()
{
}

/// \cond INTERNAL
::Ice::Object* XXXJobTrans::upCast(XXXJobWorker* p) { return p; }

/// \endcond

namespace
{
const ::std::string iceC_XXXJobTrans_XXXJobWorker_ids[2] =
{
    "::Ice::Object",
    "::XXXJobTrans::XXXJobWorker"
};

}

bool
XXXJobTrans::XXXJobWorker::ice_isA(const ::std::string& s, const ::Ice::Current&) const
{
    return ::std::binary_search(iceC_XXXJobTrans_XXXJobWorker_ids, iceC_XXXJobTrans_XXXJobWorker_ids + 2, s);
}

::std::vector< ::std::string>
XXXJobTrans::XXXJobWorker::ice_ids(const ::Ice::Current&) const
{
    return ::std::vector< ::std::string>(&iceC_XXXJobTrans_XXXJobWorker_ids[0], &iceC_XXXJobTrans_XXXJobWorker_ids[2]);
}

const ::std::string&
XXXJobTrans::XXXJobWorker::ice_id(const ::Ice::Current&) const
{
    return ice_staticId();
}

const ::std::string&
XXXJobTrans::XXXJobWorker::ice_staticId()
{
#ifdef ICE_HAS_THREAD_SAFE_LOCAL_STATIC
    static const ::std::string typeId = "::XXXJobTrans::XXXJobWorker";
    return typeId;
#else
    return iceC_XXXJobTrans_XXXJobWorker_ids[1];
#endif
}

/// \cond INTERNAL
bool
XXXJobTrans::XXXJobWorker::_iceD_processXXXItem(::IceInternal::Incoming& inS, const ::Ice::Current& current)
{
    _iceCheckMode(::Ice::Normal, current.mode);
    ::Ice::InputStream* istr = inS.startReadParams();
    ::std::pair<const ::Ice::Byte*, const ::Ice::Byte*> iceP_data;
    istr->read(iceP_data);
    inS.endReadParams();
    this->processXXXItem(iceP_data, current);
    inS.writeEmptyParams();
    return true;
}
/// \endcond

/// \cond INTERNAL
bool
XXXJobTrans::XXXJobWorker::_iceD_processYYYItem(::IceInternal::Incoming& inS, const ::Ice::Current& current)
{
    _iceCheckMode(::Ice::Normal, current.mode);
    ::Ice::InputStream* istr = inS.startReadParams();
    ::std::pair<const ::Ice::Byte*, const ::Ice::Byte*> iceP_data;
    istr->read(iceP_data);
    inS.endReadParams();
    this->processYYYItem(iceP_data, current);
    inS.writeEmptyParams();
    return true;
}
/// \endcond

/// \cond INTERNAL
bool
XXXJobTrans::XXXJobWorker::_iceD_shutdown(::IceInternal::Incoming& inS, const ::Ice::Current& current)
{
    _iceCheckMode(::Ice::Normal, current.mode);
    inS.readEmptyParams();
    this->shutdown(current);
    inS.writeEmptyParams();
    return true;
}
/// \endcond

namespace
{
const ::std::string iceC_XXXJobTrans_XXXJobWorker_all[] =
{
    "ice_id",
    "ice_ids",
    "ice_isA",
    "ice_ping",
    "processXXXItem",
    "processYYYItem",
    "shutdown"
};

}

/// \cond INTERNAL
bool
XXXJobTrans::XXXJobWorker::_iceDispatch(::IceInternal::Incoming& in, const ::Ice::Current& current)
{
    ::std::pair<const ::std::string*, const ::std::string*> r = ::std::equal_range(iceC_XXXJobTrans_XXXJobWorker_all, iceC_XXXJobTrans_XXXJobWorker_all + 7, current.operation);
    if(r.first == r.second)
    {
        throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
    }

    switch(r.first - iceC_XXXJobTrans_XXXJobWorker_all)
    {
        case 0:
        {
            return _iceD_ice_id(in, current);
        }
        case 1:
        {
            return _iceD_ice_ids(in, current);
        }
        case 2:
        {
            return _iceD_ice_isA(in, current);
        }
        case 3:
        {
            return _iceD_ice_ping(in, current);
        }
        case 4:
        {
            return _iceD_processXXXItem(in, current);
        }
        case 5:
        {
            return _iceD_processYYYItem(in, current);
        }
        case 6:
        {
            return _iceD_shutdown(in, current);
        }
        default:
        {
            assert(false);
            throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
        }
    }
}
/// \endcond

/// \cond STREAM
void
XXXJobTrans::XXXJobWorker::_iceWriteImpl(::Ice::OutputStream* ostr) const
{
    ostr->startSlice(ice_staticId(), -1, true);
    ::Ice::StreamWriter< XXXJobWorker, ::Ice::OutputStream>::write(ostr, *this);
    ostr->endSlice();
}

void
XXXJobTrans::XXXJobWorker::_iceReadImpl(::Ice::InputStream* istr)
{
    istr->startSlice();
    ::Ice::StreamReader< XXXJobWorker, ::Ice::InputStream>::read(istr, *this);
    istr->endSlice();
}
/// \endcond

/// \cond INTERNAL
void
XXXJobTrans::_icePatchObjectPtr(XXXJobWorkerPtr& handle, const ::Ice::ObjectPtr& v)
{
    handle = XXXJobWorkerPtr::dynamicCast(v);
    if(v && !handle)
    {
        IceInternal::Ex::throwUOE(XXXJobWorker::ice_staticId(), v);
    }
}
/// \endcond

XXXJobTrans::XXXJobDirector::~XXXJobDirector()
{
}

/// \cond INTERNAL
::Ice::Object* XXXJobTrans::upCast(XXXJobDirector* p) { return p; }

/// \endcond

namespace
{
const ::std::string iceC_XXXJobTrans_XXXJobDirector_ids[2] =
{
    "::Ice::Object",
    "::XXXJobTrans::XXXJobDirector"
};

}

bool
XXXJobTrans::XXXJobDirector::ice_isA(const ::std::string& s, const ::Ice::Current&) const
{
    return ::std::binary_search(iceC_XXXJobTrans_XXXJobDirector_ids, iceC_XXXJobTrans_XXXJobDirector_ids + 2, s);
}

::std::vector< ::std::string>
XXXJobTrans::XXXJobDirector::ice_ids(const ::Ice::Current&) const
{
    return ::std::vector< ::std::string>(&iceC_XXXJobTrans_XXXJobDirector_ids[0], &iceC_XXXJobTrans_XXXJobDirector_ids[2]);
}

const ::std::string&
XXXJobTrans::XXXJobDirector::ice_id(const ::Ice::Current&) const
{
    return ice_staticId();
}

const ::std::string&
XXXJobTrans::XXXJobDirector::ice_staticId()
{
#ifdef ICE_HAS_THREAD_SAFE_LOCAL_STATIC
    static const ::std::string typeId = "::XXXJobTrans::XXXJobDirector";
    return typeId;
#else
    return iceC_XXXJobTrans_XXXJobDirector_ids[1];
#endif
}

/// \cond INTERNAL
bool
XXXJobTrans::XXXJobDirector::_iceD_compete(::IceInternal::Incoming& inS, const ::Ice::Current& current)
{
    _iceCheckMode(::Ice::Normal, current.mode);
    ::Ice::InputStream* istr = inS.startReadParams();
    XXXJobWorkerPrx iceP_worker;
    istr->read(iceP_worker);
    inS.endReadParams();
    bool ret = this->compete(iceP_worker, current);
    ::Ice::OutputStream* ostr = inS.startWriteParams();
    ostr->write(ret);
    inS.endWriteParams();
    return true;
}
/// \endcond

/// \cond INTERNAL
bool
XXXJobTrans::XXXJobDirector::_iceD_onXXXResult(::IceInternal::Incoming& inS, const ::Ice::Current& current)
{
    _iceCheckMode(::Ice::Normal, current.mode);
    ::Ice::InputStream* istr = inS.startReadParams();
    ::Ice::Int iceP_result;
    istr->read(iceP_result);
    inS.endReadParams();
    this->onXXXResult(iceP_result, current);
    inS.writeEmptyParams();
    return true;
}
/// \endcond

/// \cond INTERNAL
bool
XXXJobTrans::XXXJobDirector::_iceD_onYYYResult(::IceInternal::Incoming& inS, const ::Ice::Current& current)
{
    _iceCheckMode(::Ice::Normal, current.mode);
    ::Ice::InputStream* istr = inS.startReadParams();
    ::Ice::Int iceP_result;
    istr->read(iceP_result);
    inS.endReadParams();
    this->onYYYResult(iceP_result, current);
    inS.writeEmptyParams();
    return true;
}
/// \endcond

namespace
{
const ::std::string iceC_XXXJobTrans_XXXJobDirector_all[] =
{
    "compete",
    "ice_id",
    "ice_ids",
    "ice_isA",
    "ice_ping",
    "onXXXResult",
    "onYYYResult"
};

}

/// \cond INTERNAL
bool
XXXJobTrans::XXXJobDirector::_iceDispatch(::IceInternal::Incoming& in, const ::Ice::Current& current)
{
    ::std::pair<const ::std::string*, const ::std::string*> r = ::std::equal_range(iceC_XXXJobTrans_XXXJobDirector_all, iceC_XXXJobTrans_XXXJobDirector_all + 7, current.operation);
    if(r.first == r.second)
    {
        throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
    }

    switch(r.first - iceC_XXXJobTrans_XXXJobDirector_all)
    {
        case 0:
        {
            return _iceD_compete(in, current);
        }
        case 1:
        {
            return _iceD_ice_id(in, current);
        }
        case 2:
        {
            return _iceD_ice_ids(in, current);
        }
        case 3:
        {
            return _iceD_ice_isA(in, current);
        }
        case 4:
        {
            return _iceD_ice_ping(in, current);
        }
        case 5:
        {
            return _iceD_onXXXResult(in, current);
        }
        case 6:
        {
            return _iceD_onYYYResult(in, current);
        }
        default:
        {
            assert(false);
            throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
        }
    }
}
/// \endcond

/// \cond STREAM
void
XXXJobTrans::XXXJobDirector::_iceWriteImpl(::Ice::OutputStream* ostr) const
{
    ostr->startSlice(ice_staticId(), -1, true);
    ::Ice::StreamWriter< XXXJobDirector, ::Ice::OutputStream>::write(ostr, *this);
    ostr->endSlice();
}

void
XXXJobTrans::XXXJobDirector::_iceReadImpl(::Ice::InputStream* istr)
{
    istr->startSlice();
    ::Ice::StreamReader< XXXJobDirector, ::Ice::InputStream>::read(istr, *this);
    istr->endSlice();
}
/// \endcond

/// \cond INTERNAL
void
XXXJobTrans::_icePatchObjectPtr(XXXJobDirectorPtr& handle, const ::Ice::ObjectPtr& v)
{
    handle = XXXJobDirectorPtr::dynamicCast(v);
    if(v && !handle)
    {
        IceInternal::Ex::throwUOE(XXXJobDirector::ice_staticId(), v);
    }
}
/// \endcond

namespace Ice
{
}

#endif
